version: '3'
services:
  backend_test:
    build: 
      context: ./backend
      dockerfile: Dockerfile.test
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=test
      - TEST_MONGODB_URI=mongodb://mongo_test:27017/treehole_test
    depends_on:
      - mongo_test
    command: npm run test

  mongo_test:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongotestdata:/data/db

volumes:
  mongotestdata: